//
//  NonUIStrings.swift
//  ContactsApp
//
//  Created by Yuvraj Sahu on 18/12/19.
//  Copyright © 2019 Yuvraj Sahu Apps. All rights reserved.
//

let CONTACTS_LOADED_SUCCESSFULLY = "CONTACTS_LOADED_SUCCESSFULLY"
let CONTACTS_LOADING_FAILED = "CONTACTS_LOADING_FAILED"
let NEW_CONTACT_CREATED = "NEW_CONTACT_CREATED"
let NEW_CONTACT_CREATION_FAILED = "NEW_CONTACT_CREATION_FAILED"
let CONTACT_UPDATED_SUCCESSFULLY = "CONTACT_UPDATED_SUCCESSFULLY"
let CONTACT_UPDATE_FAILED = "CONTACT_UPDATE_FAILED"

let PLACEHOLDER_PHOTO = "placeholder_photo"
