//
//  NonUIStrings.swift
//  ContactsApp
//
//  Created by Yuvraj Sahu on 18/12/19.
//  Copyright © 2019 Yuvraj Sahu Apps. All rights reserved.
//

let CONTACTS_LOADED_SUCCESSFULLY = "CONTACTS_LOADED_SUCCESSFULLY"
let CONTACTS_LOADING_FAILED = "CONTACTS_LOADING_FAILED"
let NEW_CONTACT_CREATED = "NEW_CONTACT_CREATED"
let NEW_CONTACT_CREATION_FAILED = "NEW_CONTACT_CREATION_FAILED"
let CONTACT_UPDATED_SUCCESSFULLY = "CONTACT_UPDATED_SUCCESSFULLY"
let CONTACT_UPDATE_FAILED = "CONTACT_UPDATE_FAILED"

let PLACEHOLDER_PHOTO = "placeholder_photo"
let CALL_BUTTON_PHOTO = "call_button"
let CAMERA_BUTTON_PHOTO = "camera_button"
let EMAIL_BUTTON_PHOTO = "email_button"
let FAVORITE_BUTTON_PHOTO = "favourite_button"
let FAVORITE_SELECTED_BUTTON_PHOTO = "favourite_button_selected"
let HOME_FAVORITE_BUTTON_PHOTO = "home_favourite"
let MESSAGE_BUTTON_PHOTO = "message_button"

let SYSTEM_IMAGE_EXCLAIMATION_MARK_CIRCLE = "exclamationmark.circle"
